//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace variant1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material_type_import()
        {
            this.Materials_import = new HashSet<Materials_import>();
        }
    
        public Nullable<double> Номер_материала { get; set; }
        public string Тип_материала { get; set; }
        public Nullable<double> Процент_потери_сырья { get; set; }
    
        public virtual Material_product Material_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materials_import> Materials_import { get; set; }
    }
}
