//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace variant1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mateerial_suppliers_import
    {
        public double Номер { get; set; }
        public string Намиенование_материала { get; set; }
        public string Поставщик { get; set; }
    
        public virtual Materials_import Materials_import { get; set; }
        public virtual Suppliers_import Suppliers_import { get; set; }
    }
}
