//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace variant1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class variant1DbEntities : DbContext
    {
        public variant1DbEntities()
            : base("name=variant1DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mateerial_suppliers_import> Mateerial_suppliers_import { get; set; }
        public virtual DbSet<Material_product> Material_product { get; set; }
        public virtual DbSet<Material_type_import> Material_type_import { get; set; }
        public virtual DbSet<Materials_import> Materials_import { get; set; }
        public virtual DbSet<Product_type_import> Product_type_import { get; set; }
        public virtual DbSet<Suppliers_import> Suppliers_import { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
