//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace variant1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_type_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_type_import()
        {
            this.Material_product = new HashSet<Material_product>();
        }
    
        public double Номер_продукта { get; set; }
        public string Тип_продукции { get; set; }
        public Nullable<double> Коэффициент_типпа_продукции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_product> Material_product { get; set; }
    }
}
